// Official NIST SHA-3 test vectors for the full keccak module
// Auto-generated by generate_sha3_nist_vectors.py
// Sources: NIST FIPS 202 / SHA-3 Known-Answer Tests

#ifndef SHA3_NIST_VECTORS_H
#define SHA3_NIST_VECTORS_H

#include <vector>
#include <string>
#include <cstdint>

// Re-use the SHA3Variant enum from padder_test_vectors.h if already included,
// otherwise define it here.
#ifndef PADDER_TEST_VECTORS_H
enum class SHA3Variant {
    SHA3_224 = 0,
    SHA3_256 = 1,
    SHA3_384 = 2,
    SHA3_512 = 3
};
#endif

struct SHA3NISTVector {
    std::string  name;
    std::string  description;
    SHA3Variant  variant;
    // Input message encoded as big-endian 64-bit words.  The most-significant
    // byte of each word is the chronologically first byte.  E.g. "abc"
    // (0x61 0x62 0x63) is stored as {0x6162630000000000ULL} with
    // num_full_words=0, remaining_bytes=3.
    std::vector<uint64_t> input_words;
    uint32_t num_full_words;   // number of complete (8-byte) words
    uint32_t remaining_bytes;  // 0-7 valid bytes in the last word
    // Expected digest as big-endian 32-bit words.
    // SHA3-224 → 7 words, SHA3-256 → 8 words,
    // SHA3-384 → 12 words, SHA3-512 → 16 words.
    std::vector<uint32_t> expected_digest;
};

static const std::vector<SHA3NISTVector> SHA3_NIST_VECTORS = {
    // -----------------------------------------------------------------------
    // SHA3_224 (28-byte output = 7 words)
    // -----------------------------------------------------------------------

    {
        "sha3_224_empty",
        "SHA3-224 of empty string",
        SHA3Variant::SHA3_224,
        /*input_words=*/ {},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 0,
        // 6b4e0342 3667dbb7 3b6e1545 4f0eb1ab d4597f9a 1b078e3f 5b5a6bc7
        {
         0x6b4e0342, 0x3667dbb7, 0x3b6e1545, 0x4f0eb1ab,
         0xd4597f9a, 0x1b078e3f, 0x5b5a6bc7}
    },

    {
        "sha3_224_abc",
        "SHA3-224 of \"abc\" (NIST FIPS 202 Appendix A)",
        SHA3Variant::SHA3_224,
        /*input_words=*/ {0x6162630000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 3,
        // e642824c 3f8cf24a d09234ee 7d3c766f c9a3a516 8d0c94ad 73b46fdf
        {
         0xe642824c, 0x3f8cf24a, 0xd09234ee, 0x7d3c766f,
         0xc9a3a516, 0x8d0c94ad, 0x73b46fdf}
    },

    {
        "sha3_224_single_byte",
        "SHA3-224 of single byte 0x42",
        SHA3Variant::SHA3_224,
        /*input_words=*/ {0x4200000000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 1,
        // b60bd459 170afa28 b3ef45a2 2ce41ede 9ad62a9a 0b250482 a7e1beb6
        {
         0xb60bd459, 0x170afa28, 0xb3ef45a2, 0x2ce41ede,
         0x9ad62a9a, 0x0b250482, 0xa7e1beb6}
    },

    {
        "sha3_224_password123",
        "SHA3-224 of \"password123\"",
        SHA3Variant::SHA3_224,
        /*input_words=*/ {0x70617373776f7264ULL, 0x3132330000000000ULL},
        /*num_full_words=*/ 1,
        /*remaining_bytes=*/ 3,
        // cc782e54 80878ba3 fb6bb079 05fdcf4a 00e056ad b957ae8a 03c53a52
        {
         0xcc782e54, 0x80878ba3, 0xfb6bb079, 0x05fdcf4a,
         0x00e056ad, 0xb957ae8a, 0x03c53a52}
    },

    // -----------------------------------------------------------------------
    // SHA3_256 (32-byte output = 8 words)
    // -----------------------------------------------------------------------

    {
        "sha3_256_empty",
        "SHA3-256 of empty string",
        SHA3Variant::SHA3_256,
        /*input_words=*/ {},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 0,
        // a7ffc6f8 bf1ed766 51c14756 a061d662 f580ff4d e43b49fa 82d80a4b 80f8434a
        {
         0xa7ffc6f8, 0xbf1ed766, 0x51c14756, 0xa061d662,
         0xf580ff4d, 0xe43b49fa, 0x82d80a4b, 0x80f8434a}
    },

    {
        "sha3_256_abc",
        "SHA3-256 of \"abc\" (NIST FIPS 202 Appendix A)",
        SHA3Variant::SHA3_256,
        /*input_words=*/ {0x6162630000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 3,
        // 3a985da7 4fe225b2 045c172d 6bd390bd 855f086e 3e9d525b 46bfe245 11431532
        {
         0x3a985da7, 0x4fe225b2, 0x045c172d, 0x6bd390bd,
         0x855f086e, 0x3e9d525b, 0x46bfe245, 0x11431532}
    },

    {
        "sha3_256_single_byte",
        "SHA3-256 of single byte 0x42",
        SHA3Variant::SHA3_256,
        /*input_words=*/ {0x4200000000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 1,
        // 521ec188 51e17bbb a961bc46 c70baf03 ee67ebde a11a8306 de39c15a 90e9d2e5
        {
         0x521ec188, 0x51e17bbb, 0xa961bc46, 0xc70baf03,
         0xee67ebde, 0xa11a8306, 0xde39c15a, 0x90e9d2e5}
    },

    {
        "sha3_256_password123",
        "SHA3-256 of \"password123\"",
        SHA3Variant::SHA3_256,
        /*input_words=*/ {0x70617373776f7264ULL, 0x3132330000000000ULL},
        /*num_full_words=*/ 1,
        /*remaining_bytes=*/ 3,
        // ab3fe400 3f14e3ef 573417f9 5e47d498 5c482ead d139c08b 3758eeae 7cc60b9d
        {
         0xab3fe400, 0x3f14e3ef, 0x573417f9, 0x5e47d498,
         0x5c482ead, 0xd139c08b, 0x3758eeae, 0x7cc60b9d}
    },

    // -----------------------------------------------------------------------
    // SHA3_384 (48-byte output = 12 words)
    // -----------------------------------------------------------------------

    {
        "sha3_384_empty",
        "SHA3-384 of empty string",
        SHA3Variant::SHA3_384,
        /*input_words=*/ {},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 0,
        // 0c63a75b 845e4f7d 01107d85 2e4c2485 c51a50aa aa94fc61 995e71bb ee983a2a c3713831 264adb47 fb6bd1e0 58d5f004
        {
         0x0c63a75b, 0x845e4f7d, 0x01107d85, 0x2e4c2485,
         0xc51a50aa, 0xaa94fc61, 0x995e71bb, 0xee983a2a,
         0xc3713831, 0x264adb47, 0xfb6bd1e0, 0x58d5f004}
    },

    {
        "sha3_384_abc",
        "SHA3-384 of \"abc\" (NIST FIPS 202 Appendix A)",
        SHA3Variant::SHA3_384,
        /*input_words=*/ {0x6162630000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 3,
        // ec014982 88516fc9 26459f58 e2c6ad8d f9b473cb 0fc08c25 96da7cf0 e49be4b2 98d88cea 927ac7f5 39f1edf2 28376d25
        {
         0xec014982, 0x88516fc9, 0x26459f58, 0xe2c6ad8d,
         0xf9b473cb, 0x0fc08c25, 0x96da7cf0, 0xe49be4b2,
         0x98d88cea, 0x927ac7f5, 0x39f1edf2, 0x28376d25}
    },

    {
        "sha3_384_single_byte",
        "SHA3-384 of single byte 0x42",
        SHA3Variant::SHA3_384,
        /*input_words=*/ {0x4200000000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 1,
        // 8283d235 852af9bb f7d81037 b8b70aab a733a443 3a4438f1 b944c04c 9e1d9d6d 927e96d6 1b1fb7e7 ecfcf298 3ad816b5
        {
         0x8283d235, 0x852af9bb, 0xf7d81037, 0xb8b70aab,
         0xa733a443, 0x3a4438f1, 0xb944c04c, 0x9e1d9d6d,
         0x927e96d6, 0x1b1fb7e7, 0xecfcf298, 0x3ad816b5}
    },

    {
        "sha3_384_password123",
        "SHA3-384 of \"password123\"",
        SHA3Variant::SHA3_384,
        /*input_words=*/ {0x70617373776f7264ULL, 0x3132330000000000ULL},
        /*num_full_words=*/ 1,
        /*remaining_bytes=*/ 3,
        // d9b644c8 5745fe08 4746ef61 cd2b5c09 81ad524b 9ab114c1 e8896668 7479a0fb be87f09a 647a92b0 8437d1b6 3c555b06
        {
         0xd9b644c8, 0x5745fe08, 0x4746ef61, 0xcd2b5c09,
         0x81ad524b, 0x9ab114c1, 0xe8896668, 0x7479a0fb,
         0xbe87f09a, 0x647a92b0, 0x8437d1b6, 0x3c555b06}
    },

    // -----------------------------------------------------------------------
    // SHA3_512 (64-byte output = 16 words)
    // -----------------------------------------------------------------------

    {
        "sha3_512_empty",
        "SHA3-512 of empty string",
        SHA3Variant::SHA3_512,
        /*input_words=*/ {},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 0,
        // a69f73cc a23a9ac5 c8b567dc 185a756e 97c98216 4fe25859 e0d1dcc1 475c80a6 15b2123a f1f5f94c 11e3e940 2c3ac558 f500199d 95b6d3e3 01758586 281dcd26
        {
         0xa69f73cc, 0xa23a9ac5, 0xc8b567dc, 0x185a756e,
         0x97c98216, 0x4fe25859, 0xe0d1dcc1, 0x475c80a6,
         0x15b2123a, 0xf1f5f94c, 0x11e3e940, 0x2c3ac558,
         0xf500199d, 0x95b6d3e3, 0x01758586, 0x281dcd26}
    },

    {
        "sha3_512_abc",
        "SHA3-512 of \"abc\" (NIST FIPS 202 Appendix A)",
        SHA3Variant::SHA3_512,
        /*input_words=*/ {0x6162630000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 3,
        // b751850b 1a57168a 5693cd92 4b6b096e 08f62182 7444f70d 884f5d02 40d2712e 10e116e9 192af3c9 1a7ec576 47e39340 57340b4c f408d5a5 6592f827 4eec53f0
        {
         0xb751850b, 0x1a57168a, 0x5693cd92, 0x4b6b096e,
         0x08f62182, 0x7444f70d, 0x884f5d02, 0x40d2712e,
         0x10e116e9, 0x192af3c9, 0x1a7ec576, 0x47e39340,
         0x57340b4c, 0xf408d5a5, 0x6592f827, 0x4eec53f0}
    },

    {
        "sha3_512_single_byte",
        "SHA3-512 of single byte 0x42",
        SHA3Variant::SHA3_512,
        /*input_words=*/ {0x4200000000000000ULL},
        /*num_full_words=*/ 0,
        /*remaining_bytes=*/ 1,
        // 7b637bc5 543d96f4 9500aaad 3b27d8bd 37624db2 3d415c4d 0f3dd231 e9b9fb06 1f39b7d8 561c5406 50de8bef 02aca43a 2069cc25 12697bd3 4f2244ee 732743a9
        {
         0x7b637bc5, 0x543d96f4, 0x9500aaad, 0x3b27d8bd,
         0x37624db2, 0x3d415c4d, 0x0f3dd231, 0xe9b9fb06,
         0x1f39b7d8, 0x561c5406, 0x50de8bef, 0x02aca43a,
         0x2069cc25, 0x12697bd3, 0x4f2244ee, 0x732743a9}
    },

    {
        "sha3_512_password123",
        "SHA3-512 of \"password123\"",
        SHA3Variant::SHA3_512,
        /*input_words=*/ {0x70617373776f7264ULL, 0x3132330000000000ULL},
        /*num_full_words=*/ 1,
        /*remaining_bytes=*/ 3,
        // 4ad2c01f c6007f58 720b00fc 99b978c2 a17c5778 59d31fdb ba4b3a74 9de9383a c4b0738a eaf0b133 37db8bfe af9d8f87 faa236fc 3c8a68fb f23eb686 2fadb86e
        {
         0x4ad2c01f, 0xc6007f58, 0x720b00fc, 0x99b978c2,
         0xa17c5778, 0x59d31fdb, 0xba4b3a74, 0x9de9383a,
         0xc4b0738a, 0xeaf0b133, 0x37db8bfe, 0xaf9d8f87,
         0xfaa236fc, 0x3c8a68fb, 0xf23eb686, 0x2fadb86e}
    }
};

#endif // SHA3_NIST_VECTORS_H