/*
 * Testbench: f_permutation
 * ========================
 * Verifies the Keccak-f[1600] permutation module against test vectors
 * generated by generate_f_permutation_vectors.py.
 *
 * Timing (all relative to the cycle where in_ready is high):
 *   Accept cycle   : rc[0] applied, XOR input latched, rnd_idx → 1
 *   Cycles 1–22    : rc[1]..rc[22] applied
 *   Cycle 23       : rc[23] applied, done = 1
 *   Cycle 24       : out_ready = 1, result stable in dut->out
 *
 * Chain tests (prev_result_idx >= 0):
 *   The hardware state register is left as-is after a completed permutation;
 *   the next in_ready XORs the new block into it.  No reset between blocks.
 *   A chain test is skipped if its dependency failed (state would be wrong).
 *
 * Port bit layout (Verilator WData arrays, little-endian word order):
 *   dut->in[35]  = in[1151:1120]  (MSB)    dut->in[0]  = in[31:0]   (LSB)
 *   dut->out[49] = state[1599:1568](MSB)   dut->out[0] = state[31:0](LSB)
 * Our arrays are MSB-first, so:
 *   in_words[k]       --> dut->in[35 - k]
 *   expected_out[k]   --> dut->out[49 - k]
 */

#include <iostream>
#include <iomanip>
#include <cstring>
#include <string>
#include "Vf_permutation.h"
#include "verilated.h"
#include "verilated_vcd_c.h"
#include "f_permutation_test_vectors.h"

constexpr int IN_WORDS    = 36;   // MAX_RATE / 32
constexpr int STATE_WORDS = 50;   // STATE_WIDTH / 32

// ── Testbench class ───────────────────────────────────────────────────────────

class FPermTB {
public:
    Vf_permutation* dut;
    VerilatedVcdC*  trace    = nullptr;
    uint64_t        sim_time = 0;

    FPermTB() {
        dut           = new Vf_permutation;
        dut->clk      = 0;
        dut->reset    = 1;
        dut->in_ready = 0;
        for (int i = 0; i < IN_WORDS; i++)
            dut->in[i] = 0;
        dut->eval();
    }

    ~FPermTB() {
        if (trace) {
            trace->close();
            delete trace;
        }
        dut->final();
        delete dut;
    }

    void open_trace(const std::string& filename) {
        if (!trace) {
            trace = new VerilatedVcdC;
            dut->trace(trace, 99);
            trace->open(filename.c_str());
            std::cout << "Opened VCD trace: " << filename << std::endl;
        }
    }

    void close_trace() {
        if (trace) {
            trace->close();
            delete trace;
            trace = nullptr;
        }
    }

    // ── Clock ───────────────────────────────────────────────────────────────
    void tick() {
        dut->clk = 1;  dut->eval();
        if (trace) trace->dump(sim_time);
        ++sim_time;
        dut->clk = 0;  dut->eval();
        if (trace) trace->dump(sim_time);
        ++sim_time;
    }

    // ── Reset ───────────────────────────────────────────────────────────────
    void do_reset() {
        dut->reset    = 1;
        dut->in_ready = 0;
        for (int c = 0; c < 5; c++) tick();
        dut->reset = 0;
        tick();
    }

    // ── Apply in_words (MSB-first) to dut->in ───────────────────────────────
    void set_in(const uint32_t* in_words) {
        for (int k = 0; k < IN_WORDS; k++)
            dut->in[IN_WORDS - 1 - k] = in_words[k];
    }

    // ── Run one permutation and return pass/fail ─────────────────────────────
    // Called after reset OR after a previous permutation completed.
    bool run(const FPermTestVector& tv, bool show_all_mismatches = true) {
        // Feed the block for exactly one cycle
        set_in(tv.in_words);
        dut->in_ready = 1;
        tick();
        dut->in_ready = 0;

        // Wait for out_ready (max 30 cycles; exactly 24 expected)
        int cycles = 0;
        while (!dut->out_ready && cycles < 30) {
            tick();
            ++cycles;
        }

        if (!dut->out_ready) {
            std::cout << "[FAIL] " << tv.name
                      << " — timeout waiting for out_ready" << std::endl;
            return false;
        }

        // Compare output
        bool pass = true;
        for (int k = 0; k < STATE_WORDS; k++) {
            uint32_t got = dut->out[STATE_WORDS - 1 - k];
            uint32_t exp = tv.expected_out[k];
            if (got != exp) {
                if (pass) {
                    std::cout << "[FAIL] " << tv.name << std::endl;
                    pass = false;
                }
                if (show_all_mismatches) {
                    // Which Python lane does this word belong to?
                    int lane_idx = k / 2;       // 0-24
                    int x        = (lane_idx % 5);
                    int y        = (lane_idx / 5);
                    const char* half = (k % 2 == 0) ? "hi" : "lo";
                    std::cout << "  out[" << std::setw(2) << k << "]"
                              << " A[" << x << "][" << y << "] " << half
                              << ": expected=0x" << std::hex << std::setw(8) << std::setfill('0') << exp
                              << " got=0x"       << std::setw(8) << got
                              << std::dec << std::setfill(' ') << std::endl;
                }
            }
        }

        if (pass)
            std::cout << "[PASS] " << tv.name
                      << "  (out_ready after " << cycles << " calc cycles)"
                      << std::endl;

        return pass;
    }
};


// ── Entry point ───────────────────────────────────────────────────────────────

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);

    bool        enable_trace = false;
    std::string trace_file   = "f_permutation_trace.vcd";

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--trace") {
            enable_trace = true;
            if (i + 1 < argc && argv[i + 1][0] != '-') {
                trace_file = argv[i + 1];
                ++i;
            }
        } else if (arg == "--help" || arg == "-h") {
            std::cout << "Usage: " << argv[0] << " [--trace [filename.vcd]]" << std::endl;
            std::cout << "  --trace [file]  Enable VCD waveform output (default: f_permutation_trace.vcd)" << std::endl;
            return 0;
        }
    }

    Verilated::traceEverOn(true);

    FPermTB tb;

    if (enable_trace)
        tb.open_trace(trace_file);

    std::cout << "========================================" << std::endl;
    std::cout << "f_permutation Module Test Suite"         << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << "Test vectors: " << NUM_F_PERM_TEST_VECTORS << std::endl << std::endl;

    int passed = 0, failed = 0, skipped = 0;

    // Track which tests passed so we know whether a chain test is safe to run
    bool ok[NUM_F_PERM_TEST_VECTORS] = {};

    for (int i = 0; i < NUM_F_PERM_TEST_VECTORS; i++) {
        const FPermTestVector& tv = F_PERM_TEST_VECTORS[i];

        std::cout << "\n[" << i << "] " << tv.name << std::endl;
        std::cout << "     " << tv.description << std::endl;

        if (tv.prev_result_idx == -1) {
            // Independent test — start from a clean reset
            tb.do_reset();
        } else {
            // Chain test — hardware state must carry over from the dependency
            int dep = tv.prev_result_idx;
            if (!ok[dep]) {
                std::cout << "[SKIP] Dependency [" << dep
                          << "] failed; chain test skipped." << std::endl;
                ++skipped;
                continue;
            }
            // No reset; hardware holds the output of the previous permutation
        }

        bool result = tb.run(tv);
        ok[i] = result;
        if (result) ++passed;
        else        ++failed;
    }

    int total = NUM_F_PERM_TEST_VECTORS - skipped;
    std::cout << "\n========================================" << std::endl;
    std::cout << "Passed:  " << passed  << " / " << total << std::endl;
    std::cout << "Failed:  " << failed                     << std::endl;
    if (skipped)
        std::cout << "Skipped: " << skipped << " (chain dependency failed)" << std::endl;

    if (enable_trace) {
        tb.close_trace();
        std::cout << "\nVCD trace written to: " << trace_file << std::endl;
    }

    if (failed == 0 && skipped == 0) {
        std::cout << "\n✓ ALL TESTS PASSED!" << std::endl;
        return 0;
    } else {
        std::cout << "\n✗ SOME TESTS FAILED!" << std::endl;
        return 1;
    }
}
