#!/usr/bin/env python3
"""
Generate Test Vectors for SHA-3 Round Module
==============================================
This script generates test vectors for validating the hardware implementation
of a single Keccak-f[1600] round.

Output Format:
--------------
- C++ header file with test vectors containing:
  - Input state (1600 bits)
  - Round constant (64 bits)
  - Expected output state (1600 bits)

Note: Developed with the assistance of GitHub Copilot.
"""

import sys
import os

# Add the current directory to path to import sha3
sys.path.insert(0, os.path.dirname(__file__))
from sha3 import SHA3_Instrumented


def compute_round_constant(round_index):
    """
    Compute the round constant for a given round index using LFSR.
    This matches the iota() method in SHA3_Instrumented.
    """
    R = 1
    for i in range(round_index + 1):
        round_constant = 0
        for j in range(7):
            R = ((R << 1) ^ ((R >> 7) * 0x71)) % 256
            if (R & 2):
                round_constant ^= (1 << ((1 << j) - 1))
        if i == round_index:
            return round_constant
    return 0


def state_to_flat_bits(lanes):
    """
    Convert 5x5 lane array to a flat 1600-bit state.
    Matches the bit ordering used in the hardware (high_pos/low_pos functions).
    
    The state is organized as: A[x,y,z] = S[w(5y+x)+z]
    Where w=64 (lane width), so lane (x,y) occupies bits [64*(5y+x)+63 : 64*(5y+x)]
    
    In hardware, we use STATE_WIDTH-1 downto 0, so we reverse the indexing:
    high_pos(x,y) = STATE_WIDTH - 1 - LANE_WIDTH * (GRID_SIZE * y + x)
    low_pos(x,y) = high_pos(x,y) - (LANE_WIDTH - 1)
    """
    STATE_WIDTH = 1600
    LANE_WIDTH = 64
    GRID_SIZE = 5
    
    state_bits = [0] * STATE_WIDTH
    
    for y in range(GRID_SIZE):
        for x in range(GRID_SIZE):
            lane_value = lanes[x][y]
            # Calculate bit positions (matching hardware)
            high_pos = STATE_WIDTH - 1 - LANE_WIDTH * (GRID_SIZE * y + x)
            low_pos = high_pos - (LANE_WIDTH - 1)
            
            # Place lane bits into state
            for bit_idx in range(LANE_WIDTH):
                state_bits[low_pos + bit_idx] = (lane_value >> bit_idx) & 1
    
    return state_bits


def flat_bits_to_hex_string(bits):
    """Convert a list of bits to a hex string (for display)."""
    # Group bits into nibbles (4 bits)
    hex_chars = []
    for i in range(0, len(bits), 4):
        nibble = bits[i:i+4]
        # Reverse nibble to match conventional bit ordering
        value = sum(bit << idx for idx, bit in enumerate(nibble))
        hex_chars.append(f"{value:x}")
    
    return ''.join(reversed(hex_chars))


def generate_test_vector(test_name, initial_state_pattern, round_index):
    """
    Generate a single test vector by running one round of Keccak.
    
    Args:
        test_name: Name for this test case
        initial_state_pattern: Function that generates initial lane values
        round_index: Which round constant to use (0-23)
    
    Returns:
        Dictionary with test vector data
    """
    sha3 = SHA3_Instrumented()
    
    # Initialize the state with the given pattern
    for y in range(5):
        for x in range(5):
            sha3.lanes[x][y] = initial_state_pattern(x, y)
    
    # Capture initial state
    input_state = [row[:] for row in sha3.lanes]
    
    # Run one round
    sha3.keccak_round(round_index)
    
    # Capture output state
    output_state = [row[:] for row in sha3.lanes]
    
    # Get round constant
    round_const = compute_round_constant(round_index)
    
    return {
        'name': test_name,
        'round_index': round_index,
        'input_state': input_state,
        'output_state': output_state,
        'round_constant': round_const
    }


def generate_cpp_header(test_vectors, output_file):
    """Generate C++ header file with test vectors."""
    
    with open(output_file, 'w') as f:
        f.write("// Auto-generated test vectors for SHA-3 round module\n")
        f.write("// DO NOT EDIT - Generated by generate_round_vectors.py\n\n")
        f.write("#ifndef ROUND_TEST_VECTORS_H\n")
        f.write("#define ROUND_TEST_VECTORS_H\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <string>\n\n")
        
        f.write("struct RoundTestVector {\n")
        f.write("    std::string name;\n")
        f.write("    uint32_t round_index;\n")
        f.write("    uint64_t input_state[25];   // 5x5 lanes\n")
        f.write("    uint64_t round_constant;\n")
        f.write("    uint64_t output_state[25];  // 5x5 lanes\n")
        f.write("};\n\n")
        
        f.write(f"const int NUM_TEST_VECTORS = {len(test_vectors)};\n\n")
        
        f.write("const RoundTestVector test_vectors[] = {\n")
        
        for i, tv in enumerate(test_vectors):
            f.write("    {\n")
            f.write(f"        \"{tv['name']}\",\n")
            f.write(f"        {tv['round_index']},\n")
            
            # Input state - convert to linear array
            f.write("        {\n")
            for y in range(5):
                f.write("            ")
                for x in range(5):
                    lane_value = tv['input_state'][x][y]
                    f.write(f"0x{lane_value:016x}ULL")
                    if y < 4 or x < 4:
                        f.write(", ")
                f.write("\n")
            f.write("        },\n")
            
            # Round constant
            f.write(f"        0x{tv['round_constant']:016x}ULL,\n")
            
            # Output state
            f.write("        {\n")
            for y in range(5):
                f.write("            ")
                for x in range(5):
                    lane_value = tv['output_state'][x][y]
                    f.write(f"0x{lane_value:016x}ULL")
                    if y < 4 or x < 4:
                        f.write(", ")
                f.write("\n")
            f.write("        }\n")
            
            f.write("    }")
            if i < len(test_vectors) - 1:
                f.write(",")
            f.write("\n")
        
        f.write("};\n\n")
        f.write("#endif // ROUND_TEST_VECTORS_H\n")


def main():
    """Generate test vectors for round module validation."""
    
    print("Generating test vectors for SHA-3 round module...")
    print("=" * 60)
    
    test_vectors = []
    
    # Test 1: All zeros input, round 0
    test_vectors.append(generate_test_vector(
        "all_zeros_round_0",
        lambda x, y: 0x0,
        0
    ))
    
    # Test 2: Simple pattern (lane value = x + 5*y), round 0
    test_vectors.append(generate_test_vector(
        "simple_pattern_round_0",
        lambda x, y: x + 5*y,
        0
    ))
    
    # Test 3: Alternating bits pattern, round 5
    test_vectors.append(generate_test_vector(
        "alternating_pattern_round_5",
        lambda x, y: 0xAAAAAAAAAAAAAAAA if (x + y) % 2 == 0 else 0x5555555555555555,
        5
    ))
    
    # Test 4: All ones input, round 10
    test_vectors.append(generate_test_vector(
        "all_ones_round_10",
        lambda x, y: 0xFFFFFFFFFFFFFFFF,
        10
    ))
    
    # Test 5: Pseudo-random pattern (based on position), round 23 (last round)
    test_vectors.append(generate_test_vector(
        "pseudo_random_round_23",
        lambda x, y: ((x * 0x123456789ABCDEF) ^ (y * 0xFEDCBA987654321)) & 0xFFFFFFFFFFFFFFFF,
        23
    ))
    
    # Test 6: Identity-like sparse pattern, round 12
    test_vectors.append(generate_test_vector(
        "sparse_pattern_round_12",
        lambda x, y: (1 << (x + y)) if x == y else 0,
        12
    ))
    
    print(f"Generated {len(test_vectors)} test vectors\n")
    
    # Print summary
    for tv in test_vectors:
        print(f"Test: {tv['name']}")
        print(f"  Round: {tv['round_index']}")
        print(f"  Round Constant: 0x{tv['round_constant']:016x}")
        print()
    
    # Generate C++ header
    output_file = "../../tests/round_test_vectors.h"
    generate_cpp_header(test_vectors, output_file)
    print(f"Test vectors written to: {output_file}")
    print("=" * 60)
    print("Done!")


if __name__ == "__main__":
    main()
