#!/usr/bin/env python3
"""
Generator for SHA-3 NIST test vectors in C++ header format.

This script generates SHA-3 test vectors for different messages and variants,
outputting them in the format expected by the keccak testbench.

Usage:
    python3 generate_sha3_nist_vectors.py [--output FILE.h] [--msgs msg1 msg2 ...]
"""

import hashlib
import struct
import sys
from typing import List, Tuple, Dict, Any
from dataclasses import dataclass


@dataclass
class SHA3Variant:
    name: str
    enum_value: str
    hashlib_name: str
    digest_words: int  # Number of 32-bit words in output
    capacity_bits: int  # Keccak capacity
    rate_words: int  # Rate in 64-bit words


VARIANTS = [
    SHA3Variant("SHA3_224", "SHA3Variant::SHA3_224", "sha3_224", 7, 448, 18),
    SHA3Variant("SHA3_256", "SHA3Variant::SHA3_256", "sha3_256", 8, 512, 17),
    SHA3Variant("SHA3_384", "SHA3Variant::SHA3_384", "sha3_384", 12, 768, 13),
    SHA3Variant("SHA3_512", "SHA3Variant::SHA3_512", "sha3_512", 16, 1024, 9),
]


def message_to_be_words(msg: bytes) -> Tuple[List[int], int, int]:
    """
    Convert a message to big-endian 64-bit words.
    
    Returns:
        (input_words, num_full_words, remaining_bytes)
    """
    input_words = []
    num_full_64 = len(msg) // 8
    remaining = len(msg) % 8
    
    # Full 8-byte words
    for i in range(num_full_64):
        word = struct.unpack('>Q', msg[i*8:(i+1)*8])[0]
        input_words.append(word)
    
    # Partial last word (if any)
    if remaining > 0:
        partial = msg[num_full_64 * 8:]
        padded = partial + b'\x00' * (8 - remaining)
        word = struct.unpack('>Q', padded)[0]
        input_words.append(word)
    
    return input_words, num_full_64, remaining


def digest_to_be_words(digest: bytes) -> List[int]:
    """Convert a digest to big-endian 32-bit words."""
    words = []
    for i in range(0, len(digest), 4):
        word = struct.unpack('>I', digest[i:i+4])[0]
        words.append(word)
    return words


def compute_hash(variant: SHA3Variant, msg: bytes) -> bytes:
    """Compute SHA-3 hash for the given message."""
    h = hashlib.new(variant.hashlib_name)
    h.update(msg)
    return h.digest()


def generate_test_vector(name: str, description: str, variant: SHA3Variant, 
                         msg: bytes) -> Dict[str, Any]:
    """Generate a single test vector."""
    digest = compute_hash(variant, msg)
    input_words, num_full_words, remaining_bytes = message_to_be_words(msg)
    digest_words = digest_to_be_words(digest)
    
    return {
        'name': name,
        'description': description,
        'variant': variant,
        'input_words': input_words,
        'num_full_words': num_full_words,
        'remaining_bytes': remaining_bytes,
        'digest_words': digest_words,
    }


def format_input_words(words: List[int]) -> str:
    """Format input words as C++ initializer list."""
    if not words:
        return "{}"
    return "{" + ", ".join(f"0x{w:016x}ULL" for w in words) + "}"


def format_digest_words(words: List[int]) -> str:
    """Format digest words as C++ initializer list."""
    if len(words) <= 4:
        return "{" + ", ".join(f"0x{w:08x}" for w in words) + "}"
    else:
        # Multi-line format for longer digests
        lines = []
        for i in range(0, len(words), 4):
            chunk = words[i:i+4]
            lines.append("         " + ", ".join(f"0x{w:08x}" for w in chunk))
        return "{\n" + ",\n".join(lines) + "}"


def generate_vector_entry(tv: Dict[str, Any]) -> str:
    """Generate a single C++ test vector entry."""
    variant = tv['variant']
    
    # Escape quotes in the description
    escaped_desc = tv['description'].replace('"', '\\"')
    
    # Format the comment with digest
    digest_hex = " ".join(f"{w:08x}" for w in tv['digest_words'])
    
    lines = [
        "    {",
        f'        "{tv["name"]}",',
        f'        "{escaped_desc}",',
        f"        {variant.enum_value},",
        f"        /*input_words=*/ {format_input_words(tv['input_words'])},",
        f"        /*num_full_words=*/ {tv['num_full_words']},",
        f"        /*remaining_bytes=*/ {tv['remaining_bytes']},",
        f"        // {digest_hex}",
        f"        {format_digest_words(tv['digest_words'])}",
        "    }",
    ]
    return "\n".join(lines)


def generate_header(test_vectors: List[Dict[str, Any]], filename: str):
    """Generate the complete C++ header file."""
    header = [
        "// Official NIST SHA-3 test vectors for the full keccak module",
        "// Auto-generated by generate_sha3_nist_vectors.py",
        "// Sources: NIST FIPS 202 / SHA-3 Known-Answer Tests",
        "",
        "#ifndef SHA3_NIST_VECTORS_H",
        "#define SHA3_NIST_VECTORS_H",
        "",
        "#include <vector>",
        "#include <string>",
        "#include <cstdint>",
        "",
        "// Re-use the SHA3Variant enum from padder_test_vectors.h if already included,",
        "// otherwise define it here.",
        "#ifndef PADDER_TEST_VECTORS_H",
        "enum class SHA3Variant {",
        "    SHA3_224 = 0,",
        "    SHA3_256 = 1,",
        "    SHA3_384 = 2,",
        "    SHA3_512 = 3",
        "};",
        "#endif",
        "",
        "struct SHA3NISTVector {",
        "    std::string  name;",
        "    std::string  description;",
        "    SHA3Variant  variant;",
        "    // Input message encoded as big-endian 64-bit words.  The most-significant",
        "    // byte of each word is the chronologically first byte.  E.g. \"abc\"",
        "    // (0x61 0x62 0x63) is stored as {0x6162630000000000ULL} with",
        "    // num_full_words=0, remaining_bytes=3.",
        "    std::vector<uint64_t> input_words;",
        "    uint32_t num_full_words;   // number of complete (8-byte) words",
        "    uint32_t remaining_bytes;  // 0-7 valid bytes in the last word",
        "    // Expected digest as big-endian 32-bit words.",
        "    // SHA3-224 → 7 words, SHA3-256 → 8 words,",
        "    // SHA3-384 → 12 words, SHA3-512 → 16 words.",
        "    std::vector<uint32_t> expected_digest;",
        "};",
        "",
        "static const std::vector<SHA3NISTVector> SHA3_NIST_VECTORS = {",
    ]
    
    # Group vectors by variant
    current_variant = None
    for tv in test_vectors:
        variant = tv['variant']
        
        # Add section header if variant changed
        if variant != current_variant:
            if current_variant is not None:
                header.append("")
            header.append(f"    // -----------------------------------------------------------------------")
            header.append(f"    // {variant.name} ({variant.digest_words * 4}-byte output = {variant.digest_words} words)")
            header.append(f"    // -----------------------------------------------------------------------")
            current_variant = variant
        
        header.append("")
        entry = generate_vector_entry(tv)
        # Add comma after all but the last entry
        if tv != test_vectors[-1]:
            entry += ","
        header.append(entry)
    
    header.extend([
        "};",
        "",
        "#endif // SHA3_NIST_VECTORS_H",
    ])
    
    return "\n".join(header)


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Generate SHA-3 NIST test vectors in C++ header format"
    )
    parser.add_argument(
        "--output", "-o",
        default="tests/sha3_nist_vectors.h",
        help="Output file path (default: tests/sha3_nist_vectors.h)"
    )
    parser.add_argument(
        "--msgs",
        nargs="*",
        help="Custom messages to test (in addition to defaults)"
    )
    
    args = parser.parse_args()
    
    # Default test messages
    default_messages = [
        ("empty", "empty string", b""),
        ("abc", "\"abc\" (NIST FIPS 202 Appendix A)", b"abc"),
        ("single_byte", "single byte 0x42", b"\x42"),
        ("password123", "\"password123\"", b"password123"),
        ("long_145A", "145 bytes of 'A' (2 blocks for SHA3-224)", b"A" * 145),
        ("long_296pattern", "296 bytes of repeating pattern (for multi-block testing)", b"ABCDEFGH" * 37),
        ("heavy_10blk", "1000 bytes - heavy multi-block test for all variants", b"TESTDATA" * 125),
    ]
    
    # Add custom messages if provided
    custom_messages = []
    if args.msgs:
        for msg_str in args.msgs:
            custom_messages.append(
                (f"custom_{msg_str}", f"\"{msg_str}\"", msg_str.encode())
            )
    
    all_messages = default_messages + custom_messages
    
    # Generate test vectors for all variants and messages
    test_vectors = []
    for variant in VARIANTS:
        # First, add standard messages (same across all variants)
        for msg_key, msg_desc, msg_bytes in all_messages:
            # Extract variant number (224, 256, etc.)
            variant_num = variant.name.split('_')[1]
            name = f"sha3_{variant_num}_{msg_key}"
            description = f"SHA3-{variant_num} of {msg_desc}"
            tv = generate_test_vector(name, description, variant, msg_bytes)
            test_vectors.append(tv)
        
        # Add variant-specific tests: exact-boundary cases
        variant_num = variant.name.split('_')[1]
        rate_bytes = variant.rate_words * 8
        
        # Test 1: Single-block exact fit (no overflow)
        # Message fills block with data, padding (0x06 + zeros + 0x80) fits in same block
        # Message length = rate_bytes - 2 (leaves room for 0x06...0x80)
        exact_1blk_bytes = rate_bytes - 2
        exact_1blk_msg = b"X" * exact_1blk_bytes
        name = f"sha3_{variant_num}_exact_1blk_no_overflow"
        description = f"Exact 1-block boundary (no overflow): {exact_1blk_bytes} bytes of data + padding fits in 1 block"
        tv = generate_test_vector(name, description, variant, exact_1blk_msg)
        test_vectors.append(tv)
        
        # Test 2: Two-block exact fit (no overflow)
        # Message fills 1.5 blocks, padding wraps to exactly fill block 2
        # Message length = 2*rate_bytes - 2
        exact_2blk_bytes = 2 * rate_bytes - 2
        exact_2blk_msg = b"Y" * exact_2blk_bytes
        name = f"sha3_{variant_num}_exact_2blk_no_overflow"
        description = f"Exact 2-block boundary (no overflow): {exact_2blk_bytes} bytes of data + padding fits in 2 blocks"
        tv = generate_test_vector(name, description, variant, exact_2blk_msg)
        test_vectors.append(tv)
        
        # Test 3: Two-block input with padding overflow to third block
        # Message fills exactly 2 full blocks, padding requires a 3rd block
        # Message length = 2 * rate_bytes exactly
        exact_overflow_bytes = 2 * rate_bytes
        exact_overflow_msg = b"Z" * exact_overflow_bytes
        name = f"sha3_{variant_num}_exact_2blk_overflow_to_3blk"
        description = f"Exact 2-block input, padding overflows to 3rd block: {exact_overflow_bytes} bytes of data forces 3-block total"
        tv = generate_test_vector(name, description, variant, exact_overflow_msg)
        test_vectors.append(tv)
    
    # Generate and write the header file
    header_content = generate_header(test_vectors, args.output)
    
    try:
        with open(args.output, 'w') as f:
            f.write(header_content)
        num_msgs = len(all_messages) + 3  # +3 for variant-specific exact_1blk, exact_2blk, exact_3blk
        print(f"✓ Generated {len(test_vectors)} test vectors in {args.output}")
        print(f"  - {len(VARIANTS)} SHA3 variants")
        print(f"  - {num_msgs} message types per variant (including 3 exact-boundary tests)")
    except IOError as e:
        print(f"✗ Error writing to {args.output}: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
