#!/usr/bin/env python3
"""
Generate test vectors for the padder module.

This script generates comprehensive test cases for the SHA-3 padder, including:
- Different message lengths (short, medium, near-boundary)
- All SHA-3 variants (224, 256, 384, 512)
- Partial byte handling
- Edge cases (empty message, full blocks)

Output format is a C++ header file with test vectors.
"""

import sys
from pathlib import Path

# Import the tested and verified padding function
from pad10star1 import pad10star1

# Test messages with varying characteristics
TEST_CASES = [
    {
        'name': 'empty',
        'message': b'',
        'description': 'Empty message (padding only)'
    },
    {
        'name': 'single_byte',
        'message': b'\x42',
        'description': 'Single byte 0x42'
    },
    {
        'name': 'abc',
        'message': b'abc',
        'description': 'Classic abc test vector'
    },
    {
        'name': 'four_bytes',
        'message': b'\xAA\xBB\xCC\xDD',
        'description': 'Exactly 4 bytes (one full word)'
    },
    {
        'name': 'five_bytes',
        'message': b'HELLO',
        'description': 'Five bytes (partial second word)'
    },
    {
        'name': 'medium',
        'message': b'The quick brown fox jumps over the lazy dog',
        'description': 'Medium-length message (43 bytes)'
    },
    {
        'name': 'boundary_sha3_512',
        'message': b'\x00' * 71,  # 71 bytes = one byte short of SHA3-512 rate (72 bytes)
        'description': 'One byte short of SHA3-512 rate boundary'
    },
    {
        'name': 'exact_sha3_512',
        'message': b'\xFF' * 72,  # Exactly SHA3-512 rate
        'description': 'Exactly SHA3-512 rate (72 bytes)'
    },
]

# SHA-3 variant parameters
VARIANTS = {
    'SHA3_224': {'rate_bits': 1152, 'rate_bytes': 144, 'rate_words': 36, 'enum': 'SHA3_224'},
    'SHA3_256': {'rate_bits': 1088, 'rate_bytes': 136, 'rate_words': 34, 'enum': 'SHA3_256'},
    'SHA3_384': {'rate_bits': 832,  'rate_bytes': 104, 'rate_words': 26, 'enum': 'SHA3_384'},
    'SHA3_512': {'rate_bits': 576,  'rate_bytes': 72,  'rate_words': 18, 'enum': 'SHA3_512'},
}


def message_to_words(message):
    """
    Convert message bytes to 32-bit words (big-endian packing).
    
    The padder accepts data as 32-bit words. Bytes are packed into words
    with byte 0 in bits [31:24], byte 1 in [23:16], etc.
    """
    words = []
    for i in range(0, len(message), 4):
        chunk = message[i:i+4]
        # Pad chunk to 4 bytes if necessary
        chunk += b'\x00' * (4 - len(chunk))
        # Pack as big-endian 32-bit word
        word = (chunk[0] << 24) | (chunk[1] << 16) | (chunk[2] << 8) | chunk[3]
        words.append(word)
    return words


def generate_test_vector(test_case, variant_name, variant_info):
    """Generate a single test vector."""
    message = test_case['message']
    rate_bits = variant_info['rate_bits']
    rate_bytes = variant_info['rate_bytes']
    rate_words = variant_info['rate_words']
    
    # Apply SHA-3 padding using the verified pad10star1 function
    padded = pad10star1(message, rate_bits, domain_suffix=0x06)
    
    # Convert to words
    padded_words = message_to_words(padded)
    
    # Determine input characteristics
    message_len = len(message)
    num_full_words = message_len // 4
    remaining_bytes = message_len % 4
    
    # Convert message to input words
    input_words = message_to_words(message)
    
    return {
        'test_name': test_case['name'],
        'variant': variant_name,
        'variant_enum': variant_info['enum'],
        'description': test_case['description'],
        'message': message,
        'message_len': message_len,
        'num_full_words': num_full_words,
        'remaining_bytes': remaining_bytes,
        'input_words': input_words,
        'expected_output': padded_words[:rate_words],  # Ensure exactly rate_words
        'rate_words': rate_words,
    }


def generate_header_file(output_path):
    """Generate C++ header file with all test vectors."""
    
    with open(output_path, 'w') as f:
        f.write("""// Auto-generated test vectors for padder module
// Generated by generate_padder_vectors.py

#ifndef PADDER_TEST_VECTORS_H
#define PADDER_TEST_VECTORS_H

#include <vector>
#include <string>
#include <cstdint>

// SHA-3 variant enum (matches RTL)
enum class SHA3Variant {
    SHA3_224 = 0,
    SHA3_256 = 1,
    SHA3_384 = 2,
    SHA3_512 = 3
};

struct PadderTestVector {
    std::string name;
    std::string description;
    SHA3Variant variant;
    std::vector<uint32_t> input_words;  // Input data words
    uint32_t num_full_words;            // Number of complete 32-bit words
    uint32_t remaining_bytes;           // Remaining bytes (0-3) in last word
    std::vector<uint32_t> expected_output;  // Expected padded output
    uint32_t rate_words;                // Rate in 32-bit words
};

""")
        
        # Generate test vectors for each combination
        all_vectors = []
        for test_case in TEST_CASES:
            for variant_name, variant_info in VARIANTS.items():
                vec = generate_test_vector(test_case, variant_name, variant_info)
                all_vectors.append(vec)
        
        # Write test vector array
        f.write("static const std::vector<PadderTestVector> PADDER_TEST_VECTORS = {\n")
        
        for i, vec in enumerate(all_vectors):
            f.write("    {\n")
            f.write(f"        \"{vec['test_name']}_{vec['variant']}\",\n")
            f.write(f"        \"{vec['description']} ({vec['variant']})\",\n")
            f.write(f"        SHA3Variant::{vec['variant_enum']},\n")
            
            # Input words
            f.write("        {")
            for j, word in enumerate(vec['input_words']):
                if j > 0:
                    f.write(", ")
                f.write(f"0x{word:08X}")
            f.write("},\n")
            
            f.write(f"        {vec['num_full_words']},\n")
            f.write(f"        {vec['remaining_bytes']},\n")
            
            # Expected output
            f.write("        {")
            for j, word in enumerate(vec['expected_output']):
                if j > 0:
                    if j % 8 == 0:
                        f.write(",\n         ")
                    else:
                        f.write(", ")
                f.write(f"0x{word:08X}")
            f.write("},\n")
            
            f.write(f"        {vec['rate_words']}\n")
            f.write("    }")
            
            if i < len(all_vectors) - 1:
                f.write(",\n")
            else:
                f.write("\n")
        
        f.write("};\n\n")
        f.write("#endif // PADDER_TEST_VECTORS_H\n")
    
    print(f"Generated {len(all_vectors)} test vectors in {output_path}")


if __name__ == '__main__':
    script_dir = Path(__file__).parent
    output_dir = script_dir.parent.parent / 'tests'
    output_file = output_dir / 'padder_test_vectors.h'
    
    generate_header_file(output_file)
    print(f"Test vectors written to: {output_file}")
